# Generated by Django 4.2.6 on 2023-10-08 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short string that identifies a thing.', max_length=30, unique=True)),
                ('description', models.CharField(blank=True, help_text='A slightly longer string that describes a thing.', max_length=120)),
                ('quantity', models.IntegerField(default=0, help_text='An integer value between 0 and 100 (inclusive) representing the quantity of items.', validators=[django.core.validators.MinValueValidator(0, 'cannot less than 0'), django.core.validators.MaxValueValidator(100, 'Quantity cannot be more than 100.')])),
            ],
        ),
    ]
